name: flutter_simple_customize_calendar
description: This package allows users to implement a customizable calendar.
version: 2.0.0
repository: https://github.com/openusen/flutter_simple_customize_calendar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
